apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: local-app
  namespace: default
spec:
  hosts:
    - "*"  # aceita qualquer host
  gateways:
    - local-gateway
  http:
    - route:
        - destination:
            host: local-app
            port:
              number: 8080
